### ISSUE TITLE
Error while executing demo.py on cpu?

### ISSUE THREAD

**Issue by search4mahesh** [see--/natural-question-answering#2]
Hello,
I am getting following error while executing demo.py with custom document text(more text) on CPU. It works fine with GPU though.

tensorflow.python.framework.errors_impl.InvalidArgumentError:  indices[0,512] = 512 is not in [0, 512)
         [[{{node StatefulPartitionedCall/StatefulPartitionedCall/tf_bert_for_natural_question_answering/StatefulPartitionedCall/bert/StatefulPartitionedCall/embeddings/position_embeddings/embedding_lookup}}]] [Op:__inference_restored_function_body_89164]

Thanks
Mahesh

**Comment by see--** [comment]
I can't reproduce this from what you wrote. My guess is that you are trying to input more than 512 tokens (the maximum sequence length). Note that the demo is just a demo! Long sequences require some extra steps. You can find these steps in my [Kaggle Notebook](https://www.kaggle.com/seesee/submit-full).
