### ISSUE TITLE
Trying to Run Tokenizer

### ISSUE THREAD

**Issue by Ankur3107** [see--/natural-question-answering#3]
Hi see--

I am trying to add tokens by 
`tokenizer.add_tokens(add_tokens, offset=offset)`

But I got error

`TypeError: add_tokens() got an unexpected keyword argument 'offset'`

Are you using anything different?

Regards,
Ankur

**Comment by see--** [comment]
This method is only available in my transformers fork. The installation is in the README.md.

**Comment by Ankur3107** [comment]
Thanks ;)
