### ISSUE TITLE
Unable to run tfhub sample

### ISSUE THREAD

**Issue by mukundha** [see--/natural-question-answering#4]
I'm trying to run the tfhub sample, got the following error
`Model name 'tokenizer_tf2_qa' was not found in tokenizers model name list`
(I did `pip install transformers`), 
can you help?

**Comment by see--** [comment]
You have to download and unzip the tokenizer. Can you retry with c1087868?

**Comment by mukundha** [comment]
thank you! it worked (just needed to add eager execution - https://github.com/see--/natural-question-answering/pull/5)

**Comment by see--** [comment]
Thanks for the update. I will close the PR as eager execution is already the default in TF2.
